# My personal color scheme; replaced by theme imported above; should match nvim theme
[colors.bright]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.normal]
black = "0x2c2525"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.primary]
background = "#171717"
foreground = "0xfff1f3"

